language: haskell
env:
- GHCVER=7.4.2
- GHCVER=7.6.3
- GHCVER=7.8.3
- GHCVER=head
matrix:
  allow_failures:
  - env: GHCVER=head
before_install:
- ! "if [ $GHCVER = `ghc --numeric-version` ]; then\n  # Try installing some of the
  build-deps with apt-get for speed.\n  travis/cabal-apt-install --enable-tests $MODE\n
  \ export CABAL=cabal\nelse\n  # Install the GHC we want from hvr's PPA\n  travis_retry
  sudo add-apt-repository -y ppa:hvr/ghc\n  travis_retry sudo apt-get update\n  travis_retry
  sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy\n  export CABAL=cabal-1.18\n
  \ export PATH=/opt/ghc/$GHCVER/bin:$PATH\nfi\n"
- $CABAL update
- ! "if [ $GHCVER = \"head\" ] || [ $GHCVER = \"7.8.3\" ]; then\n  $CABAL install
  happy alex\n  export PATH=$HOME/.cabal/bin:$PATH\nfi\n"
install:
- $CABAL install --dependencies-only --enable-tests
- $CABAL configure -flib-Werror --enable-tests $MODE
script:
- $CABAL build
- $CABAL test --show-details=always
deploy:
  provider: hackage
  username: JonathanFischoff
  password:
    secure: pXctYT6ULqHF1GDJkuFHyxpXryYT174QbhsMXuOIBf4YFcSh4hLQIfCaL687DFQM2Az27smfCWs4wP3UT7NcAKl28lTNji8jk8ucsVzN4ImvXmJ+sq5vOO7lQqm5FaFWmLEaa57pjzerMvTL2DJTMT7agNRcNpgQs34clOJwxKo=
  on:
    repo: jfischoff/twitch
    tags: true
    all_branches: true
